DROP DATABASE IF EXISTS TODO;
CREATE DATABASE TODO;
USE TODO;
CREATE TABLE TODOS(ID INT PRIMARY KEY AUTO_INCREMENT, TASK VARCHAR(30), DESCRIPTION TINYTEXT, STATUS ENUM('INCOMPLETE', 'COMPLETE') DEFAULT ('INCOMPLETE'));
